const affirmations = [
  "Dede, you are the melody that makes my heart dance.",
  "Every sunrise reminds me of your smile, Charlene.",
  "Dede, you turn ordinary days into miracles.",
  "My love for you grows deeper with every heartbeat, Dede.",
  "Charlene, your kindness lights up my world.",
  "Dede, you are my safe place and my greatest adventure.",
  "You make distance feel small because my heart is always with you, Dede.",
  "Charlene, when I think of beauty, I think of you.",
  "Dede, loving you is the best decision of my life.",
  "You inspire me to be better every single day, Dede.",
  "Charlene, your laughter is my favorite song.",
  "Dede, I fall in love with you all over again every morning.",
  "My world feels brighter with you in it, Dede.",
  "Charlene, your love gives me strength.",
  "Dede, I admire your courage and grace.",
  "You are my dream come true, Charlene.",
  "Dede, my heart is forever yours.",
  "Every thought of you makes me smile, Dede.",
  "Charlene, your love is my guiding light.",
  "Dede, you make everything worthwhile.",
  "With you, Charlene, every moment feels magical.",
  "Dede, your soul is the most beautiful thing I’ve ever known.",
  "I cherish every memory with you, Charlene.",
  "Dede, you are the poetry in my life.",
  "Charlene, being yours is my greatest blessing.",
  "Dede, you make love feel effortless.",
  "My heart belongs to you, Charlene, always.",
  "Dede, your smile is brighter than any star.",
  "Charlene, you make me believe in miracles.",
  "Dede, I am proud to call you mine.",
  "Charlene, you are the queen of my heart.",
  "Dede, your love is my favorite gift.",
  "Every second with you feels like heaven, Charlene.",
  "Dede, you make me a better man.",
  "Charlene, my life is sweeter because of you.",
  "Dede, your presence makes me whole.",
  "You are my forever, Charlene.",
  "Dede, even the stars envy your glow.",
  "Charlene, your love is my anchor.",
  "Dede, I adore everything about you.",
  "Charlene, my heart races for you.",
  "Dede, you are the answer to my prayers.",
  "Charlene, your beauty shines inside and out.",
  "Dede, your love completes me.",
  "Charlene, you are my happiest thought.",
  "Dede, you are irreplaceable.",
  "Charlene, my world is brighter with you.",
  "Dede, you’re my sunshine on cloudy days.",
  "Charlene, I’m grateful for your love.",
  "Dede, my love for you is endless.",
  "Charlene, you make me smile effortlessly.",
  "Dede, I treasure your heart.",
  "Charlene, your touch heals me.",
  "Dede, your voice soothes my soul.",
  "Charlene, you are my heart’s song.",
  "Dede, I can’t imagine life without you.",
  "Charlene, your love is pure magic.",
  "Dede, you inspire my every dream.",
  "Charlene, my heart beats only for you.",
  "Dede, you are the calm to my storms.",
  "Charlene, I adore your spirit.",
  "Dede, I’m grateful for your love daily.",
  "Charlene, you’re my favorite forever.",
  "Dede, you are my light in the dark.",
  "Charlene, you are my greatest joy.",
  "Dede, you’re the reason I smile.",
  "Charlene, you are my soulmate.",
  "Dede, I’m proud to love you.",
  "Charlene, you’re my constant inspiration.",
  "Dede, you make my world bloom.",
  "Charlene, your love is my treasure.",
  "Dede, I’ll love you endlessly.",
  "Charlene, I admire your strength.",
  "Dede, you are my heart’s delight.",
  "Charlene, I’m happiest with you.",
  "Dede, your love fills my soul.",
  "Charlene, you are my peace.",
  "Dede, I can’t stop loving you.",
  "Charlene, you’re my miracle.",
  "Dede, you’re my guiding star.",
  "Charlene, I adore your smile.",
  "Dede, you’re my everything.",
  "Charlene, you are my forever love.",
  "Dede, I cherish you always.",
  "Charlene, you are my greatest gift.",
  "Dede, I’m lost in your love.",
  "Charlene, you’re my dream realized.",
  "Dede, you’re my love story.",
  "Charlene, my heart beats for you.",
  "Dede, I’m devoted to you.",
  "Charlene, you are my perfect match.",
  "Dede, I’ll always choose you.",
  "Charlene, I treasure your soul.",
  "Dede, you’re my heart’s desire.",
  "Charlene, your love is priceless.",
  "Dede, you’re my safe haven.",
  "Charlene, I adore your heart.",
  "Dede, you complete my life.",
  "Charlene, you’re my sunshine.",
  "Dede, your love fuels me.",
  "Charlene, I’m grateful for you daily.",
  "Dede, you are my forever blessing.",
  "Charlene, I can’t let you go.",
  "Dede, I’ll love you for eternity.",
  "Charlene, you are my happiness.",
  "Dede, you’re my heart’s home.",
  "Charlene, your beauty amazes me.",
  "Dede, you are my soul’s joy.",
  "Charlene, I adore your love.",
  "Dede, your heart is pure gold.",
  "Charlene, you make my dreams real.",
  "Dede, you’re my true love.",
  "Charlene, your love is my anchor.",
  "Dede, I’m blessed to love you.",
  "Charlene, you’re my heart’s strength.",
  "Dede, your smile warms me.",
  "Charlene, I love your spirit.",
  "Dede, I’ll stand by you always.",
  "Charlene, your touch comforts me.",
  "Dede, I adore your essence.",
  "Charlene, you’re my endless joy.",
  "Dede, your love heals me.",
  "Charlene, you are my dream come true.",
  "Dede, I’m devoted to your happiness.",
  "Charlene, you are my forever choice.",
  "Dede, your beauty is timeless.",
  "Charlene, your kindness inspires me.",
  "Dede, you’re my eternal love.",
  "Charlene, I cherish your presence.",
  "Dede, your laughter is my favorite sound.",
  "Charlene, you’re my sweetest blessing.",
  "Dede, you’re my heart’s treasure.",
  "Charlene, you are love itself.",
  "Dede, I’m happiest with you by my side.",
  "Charlene, your soul is divine.",
  "Dede, I’ll never stop loving you.",
  "Charlene, you are my guiding light.",
  "Dede, your love makes me whole.",
  "Charlene, you’re my reason to smile.",
  "Dede, you’re my forever flame.",
  "Charlene, I adore your soul deeply.",
  "Dede, your love is eternal.",
  "Charlene, you’re my perfect destiny.",
  "Dede, I’ll always hold you close.",
  "Charlene, you are my world.",
  "Dede, I’m grateful for your existence.",
  "Charlene, you’re my heart’s delight.",
  "Dede, I cherish every moment with you.",
  "Charlene, you make me feel alive.",
  "Dede, your love lifts me higher.",
  "Charlene, you are my truest blessing.",
  "Dede, you’re the best part of my life.",
  "Charlene, I’ll forever choose you.",
  "Dede, you are my greatest treasure.",
  "Charlene, I’m thankful for your love.",
  "Dede, your soul captivates me.",
  "Charlene, you’re my eternal flame.",
  "Dede, I love you without end.",
  "Charlene, you are my perfect love.",
  "Dede, you’re my sweetest dream.",
  "Charlene, you are my heart’s song.",
  "Dede, I’ll hold you forever.",
  "Charlene, your love defines me.",
  "Dede, you’re my shining star.",
  "Charlene, I adore you endlessly.",
  "Dede, you’re my happiness.",
  "Charlene, your love is my peace.",
  "Dede, I’ll never let you go.",
  "Charlene, you’re my only love.",
  "Dede, you’re my destiny.",
  "Charlene, I love you infinitely.",
  "Dede, you are my eternal sunshine.",
  "Charlene, you make my soul complete.",
  "Dede, I’m devoted to your love.",
  "Charlene, you’re my light forever.",
  "Dede, you are my soulmate eternal.",
  "Charlene, you make my life brighter.",
  "Dede, your love is my strength.",
  "Charlene, you’re my one and only.",
  "Dede, I’m yours forever.",
  "Charlene, you are my eternal joy.",
  "Dede, you complete my soul.",
  "Charlene, I’ll always love you deeply.",
  "Dede, your love is all I need.",
  "Charlene, you’re my sweetest gift.",
  "Dede, you’re my joy everlasting.",
  "Charlene, I adore your very being.",
  "Dede, you’re my life’s miracle.",
  "Charlene, you’re my true forever.",
  "Dede, I’ll love you to infinity.",
  "Charlene, you’re my heart’s passion.",
  "Dede, your love is endless light.",
  "Charlene, you’re my reason for everything.",
  "Dede, you are my endless dream.",
  "Charlene, I’ll treasure you forever.",
  "Dede, your beauty leaves me breathless.",
  "Charlene, your love is my home.",
  "Dede, I’m blessed beyond measure by you.",
  "Charlene, you are my every heartbeat.",
  "Dede, your love carries me always.",
  "Charlene, you’re my sweetest eternity.",
  "Dede, your soul shines bright in me.",
  "Charlene, you’re my eternal treasure.",
  "Dede, you’re my dream that came true.",
  "Charlene, you’re my forever happiness.",
  "Dede, you are my heart’s keeper.",
  "Charlene, you’re my love without end.",
  "Dede, I cherish your love forever.",
  "Charlene, you’re my joy unending.",
  "Dede, your love is my forever gift.",
  "Charlene, you’re my eternal blessing.",
  "Dede, I’ll never stop choosing you.",
  "Charlene, you’re my world always.",
  "Dede, you are my eternal flame.",
  "Charlene, you’re my forever light.",
  "Dede, I adore you endlessly, my love.",
  "Charlene, you’re my life’s brightest star.",
  "Dede, you’re my forever joy.",
  "Charlene, you’re my sweetest forever.",
  "Dede, you’re my eternal sunshine.",
  "Charlene, you’re my guiding love always.",
  "Dede, your love is my miracle.",
  "Charlene, you’re my perfect blessing."
];
